package unila.edu.mx.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * VtigerCrmentity generated by hbm2java
 */
@Entity
@Table(name="vtiger_crmentity"
    ,catalog="vtiger"
)
public class VtigerCrmentity  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int crmid;
     private int version;
     private int smcreatorid;
     private int smownerid;
     private int modifiedby;
     private String setype;
     private String description;
     private Date createdtime;
     private Date modifiedtime;
     private Date viewedtime;
     private String status;
     private Integer presence;
     private int deleted;
     private Integer smgroupid;
     private String source;
     private String label;
     @JsonIgnore
     private VtigerLeaddetails vtigerLeaddetails;

    public VtigerCrmentity() {
    }

	
    public VtigerCrmentity(int crmid, int smcreatorid, int smownerid, int modifiedby, Date createdtime, Date modifiedtime, int deleted) {
        this.crmid = crmid;
        this.smcreatorid = smcreatorid;
        this.smownerid = smownerid;
        this.modifiedby = modifiedby;
        this.createdtime = createdtime;
        this.modifiedtime = modifiedtime;
        this.deleted = deleted;
    }
    public VtigerCrmentity(int crmid, int smcreatorid, int smownerid, int modifiedby, String setype, String description, Date createdtime, Date modifiedtime, Date viewedtime, String status, Integer presence, int deleted, Integer smgroupid, String source, String label, VtigerLeaddetails vtigerLeaddetails) {
       this.crmid = crmid;
       this.smcreatorid = smcreatorid;
       this.smownerid = smownerid;
       this.modifiedby = modifiedby;
       this.setype = setype;
       this.description = description;
       this.createdtime = createdtime;
       this.modifiedtime = modifiedtime;
       this.viewedtime = viewedtime;
       this.status = status;
       this.presence = presence;
       this.deleted = deleted;
       this.smgroupid = smgroupid;
       this.source = source;
       this.label = label;
       this.vtigerLeaddetails = vtigerLeaddetails;
    }
   
     @Id 

    
    @Column(name="crmid", unique=true, nullable=false)
    public int getCrmid() {
        return this.crmid;
    }
    
    public void setCrmid(int crmid) {
        this.crmid = crmid;
    }

    @Version
    @Column(name="version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }

    
    @Column(name="smcreatorid", nullable=false)
    public int getSmcreatorid() {
        return this.smcreatorid;
    }
    
    public void setSmcreatorid(int smcreatorid) {
        this.smcreatorid = smcreatorid;
    }

    
    @Column(name="smownerid", nullable=false)
    public int getSmownerid() {
        return this.smownerid;
    }
    
    public void setSmownerid(int smownerid) {
        this.smownerid = smownerid;
    }

    
    @Column(name="modifiedby", nullable=false)
    public int getModifiedby() {
        return this.modifiedby;
    }
    
    public void setModifiedby(int modifiedby) {
        this.modifiedby = modifiedby;
    }

    
    @Column(name="setype", length=100)
    public String getSetype() {
        return this.setype;
    }
    
    public void setSetype(String setype) {
        this.setype = setype;
    }

    
    @Column(name="description", length=16777215)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdtime", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifiedtime", nullable=false, length=19)
    public Date getModifiedtime() {
        return this.modifiedtime;
    }
    
    public void setModifiedtime(Date modifiedtime) {
        this.modifiedtime = modifiedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="viewedtime", length=19)
    public Date getViewedtime() {
        return this.viewedtime;
    }
    
    public void setViewedtime(Date viewedtime) {
        this.viewedtime = viewedtime;
    }

    
    @Column(name="status", length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="presence")
    public Integer getPresence() {
        return this.presence;
    }
    
    public void setPresence(Integer presence) {
        this.presence = presence;
    }

    
    @Column(name="deleted", nullable=false)
    public int getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(int deleted) {
        this.deleted = deleted;
    }

    
    @Column(name="smgroupid")
    public Integer getSmgroupid() {
        return this.smgroupid;
    }
    
    public void setSmgroupid(Integer smgroupid) {
        this.smgroupid = smgroupid;
    }

    
    @Column(name="source", length=100)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

    
    @Column(name="label")
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="vtigerCrmentity")
    public VtigerLeaddetails getVtigerLeaddetails() {
        return this.vtigerLeaddetails;
    }
    
    public void setVtigerLeaddetails(VtigerLeaddetails vtigerLeaddetails) {
        this.vtigerLeaddetails = vtigerLeaddetails;
    }




}