package unila.edu.mx.model;

//Generated 9/05/2019 05:04:49 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
* VtigerContactscf generated by hbm2java
*/
@Entity
@Table(name="vtiger_contactscf"
 ,catalog="vtiger"
)
public class VtigerContactscf  implements java.io.Serializable {


  /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int contactid;
	@JsonIgnore
	private VtigerContactdetails vtigerContactdetails;
	private String cf866;
	private String cf868;
	private String cf872;

 public VtigerContactscf() {
 }

	
 public VtigerContactscf(VtigerContactdetails vtigerContactdetails) {
     this.vtigerContactdetails = vtigerContactdetails;
 }
 public VtigerContactscf(VtigerContactdetails vtigerContactdetails, String cf866, String cf868, String cf872) {
    this.vtigerContactdetails = vtigerContactdetails;
    this.cf866 = cf866;
    this.cf868 = cf868;
    this.cf872 = cf872;
 }

  @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="vtigerContactdetails"))@Id @GeneratedValue(generator="generator")

 
 @Column(name="contactid", unique=true, nullable=false)
 public int getContactid() {
     return this.contactid;
 }
 
 public void setContactid(int contactid) {
     this.contactid = contactid;
 }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
 public VtigerContactdetails getVtigerContactdetails() {
     return this.vtigerContactdetails;
 }
 
 public void setVtigerContactdetails(VtigerContactdetails vtigerContactdetails) {
     this.vtigerContactdetails = vtigerContactdetails;
 }

 
 @Column(name="cf_866")
 public String getCf866() {
     return this.cf866;
 }
 
 public void setCf866(String cf866) {
     this.cf866 = cf866;
 }

 
 @Column(name="cf_868")
 public String getCf868() {
     return this.cf868;
 }
 
 public void setCf868(String cf868) {
     this.cf868 = cf868;
 }

 
 @Column(name="cf_872")
 public String getCf872() {
     return this.cf872;
 }
 
 public void setCf872(String cf872) {
     this.cf872 = cf872;
 }




}


