package unila.edu.mx.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;


/**
 * VtigerContactdetails generated by hbm2java
 */
@Entity
@Table(name="vtiger_contactdetails"
    ,catalog="vtiger"
)
public class VtigerContactdetails  implements java.io.Serializable {

	
     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
		
	private int contactid;
	
	private VtigerCrmentity vtigerCrmentity;
	
    private String contactNo;	
	
    private Integer accountid;	
	
    private String salutation;	
	
    private String firstname;	
	
    private String lastname;	
	
    private String email;		
	
    private String phone;	
	
    private String mobile;
	
    private String title;
	
    private String department;
	
    private String fax;
	
    private String reportsto;
	
    private String training;
	
    private String usertype;
	
    private String contacttype;

    private String otheremail;
	
    private String secondaryemail;
	
    private String donotcall;
	
    private String emailoptout;
	
    private String imagename;
	
    private String reference;
	
    private String notifyOwner;
	
    private String isconvertedfromlead;
	
    private String tags;
	
    private VtigerContactscf vtigerContactscf;
    
    private VtigerContactsubdetails vtigerContactsubdetails;
    
    private VtigerContactaddress vtigerContactaddress;    
    

    public VtigerContactdetails() {
    }

	
    public VtigerContactdetails(VtigerCrmentity vtigerCrmentity, String contactNo, String lastname) {
        this.vtigerCrmentity = vtigerCrmentity;
        this.contactNo = contactNo;
        this.lastname = lastname;
    }
    public VtigerContactdetails(VtigerCrmentity vtigerCrmentity, String contactNo, Integer accountid, String salutation, String firstname, String lastname, String email, String phone, String mobile, String title, String department, String fax, String reportsto, String training, String usertype, String contacttype, String otheremail, String secondaryemail, String donotcall, String emailoptout, String imagename, String reference, String notifyOwner, String isconvertedfromlead, String tags, VtigerContactscf vtigerContactscf, VtigerContactsubdetails vtigerContactsubdetails, VtigerContactaddress vtigerContactaddress) {
       this.vtigerCrmentity = vtigerCrmentity;
       this.contactNo = contactNo;
       this.accountid = accountid;
       this.salutation = salutation;
       this.firstname = firstname;
       this.lastname = lastname;
       this.email = email;
       this.phone = phone;
       this.mobile = mobile;
       this.title = title;
       this.department = department;
       this.fax = fax;
       this.reportsto = reportsto;
       this.training = training;
       this.usertype = usertype;
       this.contacttype = contacttype;
       this.otheremail = otheremail;
       this.secondaryemail = secondaryemail;
       this.donotcall = donotcall;
       this.emailoptout = emailoptout;
       this.imagename = imagename;
       this.reference = reference;
       this.notifyOwner = notifyOwner;
       this.isconvertedfromlead = isconvertedfromlead;
       this.tags = tags;
       this.vtigerContactscf = vtigerContactscf;
       this.vtigerContactsubdetails = vtigerContactsubdetails;
       this.vtigerContactaddress = vtigerContactaddress;       
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="vtigerCrmentity"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="contactid", unique=true, nullable=false)
    public int getContactid() {
        return this.contactid;
    }
    
    public void setContactid(int contactid) {
        this.contactid = contactid;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public VtigerCrmentity getVtigerCrmentity() {
        return this.vtigerCrmentity;
    }
    
    public void setVtigerCrmentity(VtigerCrmentity vtigerCrmentity) {
        this.vtigerCrmentity = vtigerCrmentity;
    }

    
    @Column(name="contact_no", nullable=false, length=100)
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    
    @Column(name="accountid")
    public Integer getAccountid() {
        return this.accountid;
    }
    
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    
    @Column(name="salutation", length=200)
    public String getSalutation() {
        return this.salutation;
    }
    
    public void setSalutation(String salutation) {
        this.salutation = salutation;
    }

    
    @Column(name="firstname", length=40)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="lastname", nullable=false, length=80)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone", length=50)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="mobile", length=50)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="title", length=50)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="department", length=30)
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }

    
    @Column(name="fax", length=50)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="reportsto", length=30)
    public String getReportsto() {
        return this.reportsto;
    }
    
    public void setReportsto(String reportsto) {
        this.reportsto = reportsto;
    }

    
    @Column(name="training", length=50)
    public String getTraining() {
        return this.training;
    }
    
    public void setTraining(String training) {
        this.training = training;
    }

    
    @Column(name="usertype", length=50)
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    
    @Column(name="contacttype", length=50)
    public String getContacttype() {
        return this.contacttype;
    }
    
    public void setContacttype(String contacttype) {
        this.contacttype = contacttype;
    }

    
    @Column(name="otheremail", length=100)
    public String getOtheremail() {
        return this.otheremail;
    }
    
    public void setOtheremail(String otheremail) {
        this.otheremail = otheremail;
    }

    
    @Column(name="secondaryemail", length=100)
    public String getSecondaryemail() {
        return this.secondaryemail;
    }
    
    public void setSecondaryemail(String secondaryemail) {
        this.secondaryemail = secondaryemail;
    }

    
    @Column(name="donotcall", length=3)
    public String getDonotcall() {
        return this.donotcall;
    }
    
    public void setDonotcall(String donotcall) {
        this.donotcall = donotcall;
    }

    
    @Column(name="emailoptout", length=3)
    public String getEmailoptout() {
        return this.emailoptout;
    }
    
    public void setEmailoptout(String emailoptout) {
        this.emailoptout = emailoptout;
    }

    
    @Column(name="imagename", length=150)
    public String getImagename() {
        return this.imagename;
    }
    
    public void setImagename(String imagename) {
        this.imagename = imagename;
    }

    
    @Column(name="reference", length=3)
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }

    
    @Column(name="notify_owner", length=3)
    public String getNotifyOwner() {
        return this.notifyOwner;
    }
    
    public void setNotifyOwner(String notifyOwner) {
        this.notifyOwner = notifyOwner;
    }

    
    @Column(name="isconvertedfromlead", length=3)
    public String getIsconvertedfromlead() {
        return this.isconvertedfromlead;
    }
    
    public void setIsconvertedfromlead(String isconvertedfromlead) {
        this.isconvertedfromlead = isconvertedfromlead;
    }

    
    @Column(name="tags", length=1)
    public String getTags() {
        return this.tags;
    }
    
    public void setTags(String tags) {
        this.tags = tags;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="vtigerContactdetails")
    public VtigerContactscf getVtigerContactscf() {
        return this.vtigerContactscf;
    }
    
    public void setVtigerContactscf(VtigerContactscf vtigerContactscf) {
        this.vtigerContactscf = vtigerContactscf;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="vtigerContactdetails")
    public VtigerContactsubdetails getVtigerContactsubdetails() {
        return this.vtigerContactsubdetails;
    }
    
    public void setVtigerContactsubdetails(VtigerContactsubdetails vtigerContactsubdetails) {
        this.vtigerContactsubdetails = vtigerContactsubdetails;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="vtigerContactdetails")
    public VtigerContactaddress getVtigerContactaddress() {
        return this.vtigerContactaddress;
    }
    
    public void setVtigerContactaddress(VtigerContactaddress vtigerContactaddress) {
        this.vtigerContactaddress = vtigerContactaddress;
    }
}


