package unila.edu.mx.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * VtigerContactsubdetails generated by hbm2java
 */
@Entity
@Table(name="vtiger_contactsubdetails"
    ,catalog="vtiger"
)
public class VtigerContactsubdetails  implements java.io.Serializable {
	

	private static final long serialVersionUID = 1L;
	private int contactsubscriptionid;
	@JsonIgnore
     private VtigerContactdetails vtigerContactdetails;
     private String homephone;
     private String otherphone;
     private String assistant;
     private String assistantphone;
     private Date birthday;
     private Integer laststayintouchrequest;
     private Integer laststayintouchsavedate;
     private String leadsource;

    public VtigerContactsubdetails() {
    }

	
    public VtigerContactsubdetails(VtigerContactdetails vtigerContactdetails) {
        this.vtigerContactdetails = vtigerContactdetails;
    }
    public VtigerContactsubdetails(VtigerContactdetails vtigerContactdetails, String homephone, String otherphone, String assistant, String assistantphone, Date birthday, Integer laststayintouchrequest, Integer laststayintouchsavedate, String leadsource) {
       this.vtigerContactdetails = vtigerContactdetails;
       this.homephone = homephone;
       this.otherphone = otherphone;
       this.assistant = assistant;
       this.assistantphone = assistantphone;
       this.birthday = birthday;
       this.laststayintouchrequest = laststayintouchrequest;
       this.laststayintouchsavedate = laststayintouchsavedate;
       this.leadsource = leadsource;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="vtigerContactdetails"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="contactsubscriptionid", unique=true, nullable=false)
    public int getContactsubscriptionid() {
        return this.contactsubscriptionid;
    }
    
    public void setContactsubscriptionid(int contactsubscriptionid) {
        this.contactsubscriptionid = contactsubscriptionid;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public VtigerContactdetails getVtigerContactdetails() {
        return this.vtigerContactdetails;
    }
    
    public void setVtigerContactdetails(VtigerContactdetails vtigerContactdetails) {
        this.vtigerContactdetails = vtigerContactdetails;
    }

    
    @Column(name="homephone", length=50)
    public String getHomephone() {
        return this.homephone;
    }
    
    public void setHomephone(String homephone) {
        this.homephone = homephone;
    }

    
    @Column(name="otherphone", length=50)
    public String getOtherphone() {
        return this.otherphone;
    }
    
    public void setOtherphone(String otherphone) {
        this.otherphone = otherphone;
    }

    
    @Column(name="assistant", length=30)
    public String getAssistant() {
        return this.assistant;
    }
    
    public void setAssistant(String assistant) {
        this.assistant = assistant;
    }

    
    @Column(name="assistantphone", length=50)
    public String getAssistantphone() {
        return this.assistantphone;
    }
    
    public void setAssistantphone(String assistantphone) {
        this.assistantphone = assistantphone;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthday", length=10)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    
    @Column(name="laststayintouchrequest")
    public Integer getLaststayintouchrequest() {
        return this.laststayintouchrequest;
    }
    
    public void setLaststayintouchrequest(Integer laststayintouchrequest) {
        this.laststayintouchrequest = laststayintouchrequest;
    }

    
    @Column(name="laststayintouchsavedate")
    public Integer getLaststayintouchsavedate() {
        return this.laststayintouchsavedate;
    }
    
    public void setLaststayintouchsavedate(Integer laststayintouchsavedate) {
        this.laststayintouchsavedate = laststayintouchsavedate;
    }

    
    @Column(name="leadsource", length=200)
    public String getLeadsource() {
        return this.leadsource;
    }
    
    public void setLeadsource(String leadsource) {
        this.leadsource = leadsource;
    }




}


