package unila.edu.mx.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VtigerCf864 generated by hbm2java
 */
@Entity
@Table(name="vtiger_cf_864"
    ,catalog="vtiger"
)
public class VtigerCf864  implements java.io.Serializable {


     /**
	 * 
	 */
	
	private static final long serialVersionUID = 1L;
	private Integer cf864id;
	private String cf864;
	private int presence;
	private int picklistValueid;
	private Integer sortorderid;
	private String color;
	private int instIncorp;
	private int idGea;

    public VtigerCf864() {
    }

	
    public VtigerCf864(String cf864, int presence, int picklistValueid) {
        this.cf864 = cf864;
        this.presence = presence;
        this.picklistValueid = picklistValueid;
    }
    public VtigerCf864(String cf864, int presence, int picklistValueid, Integer sortorderid, String color, int instIncorp, int idGea) {
       this.cf864 = cf864;
       this.presence = presence;
       this.picklistValueid = picklistValueid;
       this.sortorderid = sortorderid;
       this.color = color;
       this.instIncorp = instIncorp;
       this.idGea = idGea;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cf_864id", unique=true, nullable=false)
    public Integer getCf864id() {
        return this.cf864id;
    }
    
    public void setCf864id(Integer cf864id) {
        this.cf864id = cf864id;
    }

    
    @Column(name="cf_864", nullable=false, length=200)
    public String getCf864() {
        return this.cf864;
    }
    
    public void setCf864(String cf864) {
        this.cf864 = cf864;
    }

    
    @Column(name="presence", nullable=false)
    public int getPresence() {
        return this.presence;
    }
    
    public void setPresence(int presence) {
        this.presence = presence;
    }

    
    @Column(name="picklist_valueid", nullable=false)
    public int getPicklistValueid() {
        return this.picklistValueid;
    }
    
    public void setPicklistValueid(int picklistValueid) {
        this.picklistValueid = picklistValueid;
    }

    
    @Column(name="sortorderid")
    public Integer getSortorderid() {
        return this.sortorderid;
    }
    
    public void setSortorderid(Integer sortorderid) {
        this.sortorderid = sortorderid;
    }

    
    @Column(name="color", length=10)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }


    @Column(name="inst_incorp")
    public int getInstIncorp() {
        return this.instIncorp;
    }
    
    public void setInstIncorp(int instIncorp) {
        this.instIncorp = instIncorp;
    }
    
    @Column(name="id_gea")
    public int getIdGea() {
        return this.idGea;
    }
    
    public void setIdGea(int idGea) {
        this.idGea = idGea;
    }

}


