package unila.edu.mx.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * VtigerLeaddetails generated by hbm2java
 */
@Entity
@Table(name="vtiger_leaddetails"
    ,catalog="vtiger"
)
public class VtigerLeaddetails  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int leadid;
     private VtigerCrmentity vtigerCrmentity;
     private String leadNo;
     private String email;
     private String interest;
     private String firstname;
     private String salutation;
     private String lastname;
     private String company;
     private BigDecimal annualrevenue;
     private String industry;
     private String campaign;
     private String rating;
     private String leadstatus;
     private String leadsource;
     private Integer converted;
     private String designation;
     private String licencekeystatus;
     private String space;
     private String comments;
     private String priority;
     private String demorequest;
     private String partnercontact;
     private String productversion;
     private String product;
     private Date maildate;
     private Date nextstepdate;
     private String fundingsituation;
     private String purpose;
     private String evaluationstatus;
     private Date transferdate;
     private String revenuetype;
     private Integer noofemployees;
     private String secondaryemail;
     private Integer assignleadchk;
     private String emailoptout;
     private String tags;

    public VtigerLeaddetails() {
    }

	
    public VtigerLeaddetails(VtigerCrmentity vtigerCrmentity, String leadNo, String lastname, String company) {
        this.vtigerCrmentity = vtigerCrmentity;
        this.leadNo = leadNo;
        this.lastname = lastname;
        this.company = company;
    }
    public VtigerLeaddetails(VtigerCrmentity vtigerCrmentity, String leadNo, String email, String interest, String firstname, String salutation, String lastname, String company, BigDecimal annualrevenue, String industry, String campaign, String rating, String leadstatus, String leadsource, Integer converted, String designation, String licencekeystatus, String space, String comments, String priority, String demorequest, String partnercontact, String productversion, String product, Date maildate, Date nextstepdate, String fundingsituation, String purpose, String evaluationstatus, Date transferdate, String revenuetype, Integer noofemployees, String secondaryemail, Integer assignleadchk, String emailoptout, String tags) {
       this.vtigerCrmentity = vtigerCrmentity;
       this.leadNo = leadNo;
       this.email = email;
       this.interest = interest;
       this.firstname = firstname;
       this.salutation = salutation;
       this.lastname = lastname;
       this.company = company;
       this.annualrevenue = annualrevenue;
       this.industry = industry;
       this.campaign = campaign;
       this.rating = rating;
       this.leadstatus = leadstatus;
       this.leadsource = leadsource;
       this.converted = converted;
       this.designation = designation;
       this.licencekeystatus = licencekeystatus;
       this.space = space;
       this.comments = comments;
       this.priority = priority;
       this.demorequest = demorequest;
       this.partnercontact = partnercontact;
       this.productversion = productversion;
       this.product = product;
       this.maildate = maildate;
       this.nextstepdate = nextstepdate;
       this.fundingsituation = fundingsituation;
       this.purpose = purpose;
       this.evaluationstatus = evaluationstatus;
       this.transferdate = transferdate;
       this.revenuetype = revenuetype;
       this.noofemployees = noofemployees;
       this.secondaryemail = secondaryemail;
       this.assignleadchk = assignleadchk;
       this.emailoptout = emailoptout;
       this.tags = tags;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="vtigerCrmentity"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="leadid", unique=true, nullable=false)
    public int getLeadid() {
        return this.leadid;
    }
    
    public void setLeadid(int leadid) {
        this.leadid = leadid;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public VtigerCrmentity getVtigerCrmentity() {
        return this.vtigerCrmentity;
    }
    
    public void setVtigerCrmentity(VtigerCrmentity vtigerCrmentity) {
        this.vtigerCrmentity = vtigerCrmentity;
    }

    
    @Column(name="lead_no", nullable=false, length=100)
    public String getLeadNo() {
        return this.leadNo;
    }
    
    public void setLeadNo(String leadNo) {
        this.leadNo = leadNo;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="interest", length=50)
    public String getInterest() {
        return this.interest;
    }
    
    public void setInterest(String interest) {
        this.interest = interest;
    }

    
    @Column(name="firstname", length=40)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="salutation", length=200)
    public String getSalutation() {
        return this.salutation;
    }
    
    public void setSalutation(String salutation) {
        this.salutation = salutation;
    }

    
    @Column(name="lastname", nullable=false, length=80)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="company", nullable=false, length=100)
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }

    
    @Column(name="annualrevenue", precision=25, scale=8)
    public BigDecimal getAnnualrevenue() {
        return this.annualrevenue;
    }
    
    public void setAnnualrevenue(BigDecimal annualrevenue) {
        this.annualrevenue = annualrevenue;
    }

    
    @Column(name="industry", length=200)
    public String getIndustry() {
        return this.industry;
    }
    
    public void setIndustry(String industry) {
        this.industry = industry;
    }

    
    @Column(name="campaign", length=30)
    public String getCampaign() {
        return this.campaign;
    }
    
    public void setCampaign(String campaign) {
        this.campaign = campaign;
    }

    
    @Column(name="rating", length=200)
    public String getRating() {
        return this.rating;
    }
    
    public void setRating(String rating) {
        this.rating = rating;
    }

    
    @Column(name="leadstatus", length=200)
    public String getLeadstatus() {
        return this.leadstatus;
    }
    
    public void setLeadstatus(String leadstatus) {
        this.leadstatus = leadstatus;
    }

    
    @Column(name="leadsource", length=200)
    public String getLeadsource() {
        return this.leadsource;
    }
    
    public void setLeadsource(String leadsource) {
        this.leadsource = leadsource;
    }

    
    @Column(name="converted")
    public Integer getConverted() {
        return this.converted;
    }
    
    public void setConverted(Integer converted) {
        this.converted = converted;
    }

    
    @Column(name="designation", length=50)
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    
    @Column(name="licencekeystatus", length=50)
    public String getLicencekeystatus() {
        return this.licencekeystatus;
    }
    
    public void setLicencekeystatus(String licencekeystatus) {
        this.licencekeystatus = licencekeystatus;
    }

    
    @Column(name="space", length=250)
    public String getSpace() {
        return this.space;
    }
    
    public void setSpace(String space) {
        this.space = space;
    }

    
    @Column(name="comments", length=65535)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="priority", length=50)
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }

    
    @Column(name="demorequest", length=50)
    public String getDemorequest() {
        return this.demorequest;
    }
    
    public void setDemorequest(String demorequest) {
        this.demorequest = demorequest;
    }

    
    @Column(name="partnercontact", length=50)
    public String getPartnercontact() {
        return this.partnercontact;
    }
    
    public void setPartnercontact(String partnercontact) {
        this.partnercontact = partnercontact;
    }

    
    @Column(name="productversion", length=20)
    public String getProductversion() {
        return this.productversion;
    }
    
    public void setProductversion(String productversion) {
        this.productversion = productversion;
    }

    
    @Column(name="product", length=50)
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="maildate", length=10)
    public Date getMaildate() {
        return this.maildate;
    }
    
    public void setMaildate(Date maildate) {
        this.maildate = maildate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="nextstepdate", length=10)
    public Date getNextstepdate() {
        return this.nextstepdate;
    }
    
    public void setNextstepdate(Date nextstepdate) {
        this.nextstepdate = nextstepdate;
    }

    
    @Column(name="fundingsituation", length=50)
    public String getFundingsituation() {
        return this.fundingsituation;
    }
    
    public void setFundingsituation(String fundingsituation) {
        this.fundingsituation = fundingsituation;
    }

    
    @Column(name="purpose", length=50)
    public String getPurpose() {
        return this.purpose;
    }
    
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }

    
    @Column(name="evaluationstatus", length=50)
    public String getEvaluationstatus() {
        return this.evaluationstatus;
    }
    
    public void setEvaluationstatus(String evaluationstatus) {
        this.evaluationstatus = evaluationstatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="transferdate", length=10)
    public Date getTransferdate() {
        return this.transferdate;
    }
    
    public void setTransferdate(Date transferdate) {
        this.transferdate = transferdate;
    }

    
    @Column(name="revenuetype", length=50)
    public String getRevenuetype() {
        return this.revenuetype;
    }
    
    public void setRevenuetype(String revenuetype) {
        this.revenuetype = revenuetype;
    }

    
    @Column(name="noofemployees")
    public Integer getNoofemployees() {
        return this.noofemployees;
    }
    
    public void setNoofemployees(Integer noofemployees) {
        this.noofemployees = noofemployees;
    }

    
    @Column(name="secondaryemail", length=100)
    public String getSecondaryemail() {
        return this.secondaryemail;
    }
    
    public void setSecondaryemail(String secondaryemail) {
        this.secondaryemail = secondaryemail;
    }

    
    @Column(name="assignleadchk")
    public Integer getAssignleadchk() {
        return this.assignleadchk;
    }
    
    public void setAssignleadchk(Integer assignleadchk) {
        this.assignleadchk = assignleadchk;
    }

    
    @Column(name="emailoptout", length=3)
    public String getEmailoptout() {
        return this.emailoptout;
    }
    
    public void setEmailoptout(String emailoptout) {
        this.emailoptout = emailoptout;
    }

    
    @Column(name="tags", length=1)
    public String getTags() {
        return this.tags;
    }
    
    public void setTags(String tags) {
        this.tags = tags;
    }




}


