package unila.edu.mx.model;

//Generated 9/05/2019 05:04:49 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
* VtigerContactaddress generated by hbm2java
*/
@Entity
@Table(name="vtiger_contactaddress"
 ,catalog="vtiger"
)
public class VtigerContactaddress  implements java.io.Serializable {


  /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
private int contactaddressid;
@JsonIgnore
  private VtigerContactdetails vtigerContactdetails;
  private String mailingcity;
  private String mailingstreet;
  private String mailingcountry;
  private String othercountry;
  private String mailingstate;
  private String mailingpobox;
  private String othercity;
  private String otherstate;
  private String mailingzip;
  private String otherzip;
  private String otherstreet;
  private String otherpobox;

 public VtigerContactaddress() {
 }

	
 public VtigerContactaddress(VtigerContactdetails vtigerContactdetails) {
     this.vtigerContactdetails = vtigerContactdetails;
 }
 public VtigerContactaddress(VtigerContactdetails vtigerContactdetails, String mailingcity, String mailingstreet, String mailingcountry, String othercountry, String mailingstate, String mailingpobox, String othercity, String otherstate, String mailingzip, String otherzip, String otherstreet, String otherpobox) {
    this.vtigerContactdetails = vtigerContactdetails;
    this.mailingcity = mailingcity;
    this.mailingstreet = mailingstreet;
    this.mailingcountry = mailingcountry;
    this.othercountry = othercountry;
    this.mailingstate = mailingstate;
    this.mailingpobox = mailingpobox;
    this.othercity = othercity;
    this.otherstate = otherstate;
    this.mailingzip = mailingzip;
    this.otherzip = otherzip;
    this.otherstreet = otherstreet;
    this.otherpobox = otherpobox;
 }

  @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="vtigerContactdetails"))@Id @GeneratedValue(generator="generator")

 
 @Column(name="contactaddressid", unique=true, nullable=false)
 public int getContactaddressid() {
     return this.contactaddressid;
 }
 
 public void setContactaddressid(int contactaddressid) {
     this.contactaddressid = contactaddressid;
 }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
 public VtigerContactdetails getVtigerContactdetails() {
     return this.vtigerContactdetails;
 }
 
 public void setVtigerContactdetails(VtigerContactdetails vtigerContactdetails) {
     this.vtigerContactdetails = vtigerContactdetails;
 }

 
 @Column(name="mailingcity", length=40)
 public String getMailingcity() {
     return this.mailingcity;
 }
 
 public void setMailingcity(String mailingcity) {
     this.mailingcity = mailingcity;
 }

 
 @Column(name="mailingstreet", length=250)
 public String getMailingstreet() {
     return this.mailingstreet;
 }
 
 public void setMailingstreet(String mailingstreet) {
     this.mailingstreet = mailingstreet;
 }

 
 @Column(name="mailingcountry", length=40)
 public String getMailingcountry() {
     return this.mailingcountry;
 }
 
 public void setMailingcountry(String mailingcountry) {
     this.mailingcountry = mailingcountry;
 }

 
 @Column(name="othercountry", length=30)
 public String getOthercountry() {
     return this.othercountry;
 }
 
 public void setOthercountry(String othercountry) {
     this.othercountry = othercountry;
 }

 
 @Column(name="mailingstate", length=30)
 public String getMailingstate() {
     return this.mailingstate;
 }
 
 public void setMailingstate(String mailingstate) {
     this.mailingstate = mailingstate;
 }

 
 @Column(name="mailingpobox", length=30)
 public String getMailingpobox() {
     return this.mailingpobox;
 }
 
 public void setMailingpobox(String mailingpobox) {
     this.mailingpobox = mailingpobox;
 }

 
 @Column(name="othercity", length=40)
 public String getOthercity() {
     return this.othercity;
 }
 
 public void setOthercity(String othercity) {
     this.othercity = othercity;
 }

 
 @Column(name="otherstate", length=50)
 public String getOtherstate() {
     return this.otherstate;
 }
 
 public void setOtherstate(String otherstate) {
     this.otherstate = otherstate;
 }

 
 @Column(name="mailingzip", length=30)
 public String getMailingzip() {
     return this.mailingzip;
 }
 
 public void setMailingzip(String mailingzip) {
     this.mailingzip = mailingzip;
 }

 
 @Column(name="otherzip", length=30)
 public String getOtherzip() {
     return this.otherzip;
 }
 
 public void setOtherzip(String otherzip) {
     this.otherzip = otherzip;
 }

 
 @Column(name="otherstreet", length=250)
 public String getOtherstreet() {
     return this.otherstreet;
 }
 
 public void setOtherstreet(String otherstreet) {
     this.otherstreet = otherstreet;
 }

 
 @Column(name="otherpobox", length=30)
 public String getOtherpobox() {
     return this.otherpobox;
 }
 
 public void setOtherpobox(String otherpobox) {
     this.otherpobox = otherpobox;
 }




}


